create table
  public.users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name character varying not null,
    email character varying not null,
    password character varying not null,
    user_img character varying null,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email)
  ) tablespace pg_default;

create table
  public.pets (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    owner bigint not null,
    name character varying not null,
    species character varying not null,
    breed character varying not null,
    birthday date not null,
    weight real not null,
    description text null,
    gender character varying not null,
    pet_img character varying null,
    constraint pets_pkey primary key (id),
    constraint pets_id_key unique (id),
    constraint pets_owner_fkey foreign key (owner) references users (id)
  ) tablespace pg_default;

  CREATE TABLE vaccines (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);


drop table pet_vaccinations;

CREATE TABLE pet_vaccinations (
    dataHora TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    status VARCHAR(50) NOT NULL,
    local VARCHAR(255) NOT NULL,
    id SERIAL PRIMARY KEY,
    pet_id INTEGER NOT NULL,
    vaccine_id INTEGER NOT NULL,
    next_due_date DATE,
    FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE,
    FOREIGN KEY (vaccine_id) REFERENCES vaccines(id) ON DELETE CASCADE
);


DROP TABLE medical_history;

CREATE TABLE medical_history (
    data DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    id SERIAL PRIMARY KEY,
    pet_id INTEGER NOT NULL,
    FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE
);

